repos:
  - repo: https://github.com/mineiros-io/pre-commit-hooks
    rev: v0.1.3
    hooks:
      - id: terraform-fmt
      - id: terraform-validate
        exclude: ^examples|.terraform/
      - id: tflint
      - id: gofmt
      - id: goimports
      - id: golint
      - id: phony-targets
      # golangci-lint can be used as a replacement for golint
      # - id: golangci-lint
      # markdown-link-check should only be used for public repositories TODO: implement ignore pattern for private repos
      # - id: markdown-link-check
